Never_Miss_The_Bus/Client/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from Client import views

urlpatterns = [
	url(r'^$', login_required(views.client_home), name='client_home'),
	url(r'^test/$', views.client_home1),
]

Never_Miss_The_Bus/Never_Miss_The_Bus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [
    #django urls
    url(r'^admin/', include(admin.site.urls)),
    #django-registration-redux urls
    url(r'^accounts/', include('registration.backends.default.urls')),
    #Custom apps' urls
    url(r'^app_admin/', include('App_Admin.urls', app_name="App_Admin",namespace='admin-app')),
    url(r'^client/', include('Client.urls', app_name="Client_App",namespace='client-app')),
    url(r'^$', views.home, name='home'),
]

Never_Miss_The_Bus/Client/models.py
from django.db import models
from App_Admin.models import User

# Create your models here.

Never_Miss_The_Bus/Client/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from App_Admin.models import Bus, Route
import json
# from django.utils import simplejson
# Create your views here.

# def client_home(request):
# 	buses = Bus.objects.all()
# 	template = "client_home_1.html"
# 	# template = "client_home.html"
# 	context = {'buses' : buses}
# 	if request.method == 'POST':
# 		selected_bus = request.POST.get('bus_select')
# 		# print(selected_bus)
# 		selected_bus = get_object_or_404(Bus, pk=selected_bus)
# 		selected_bus_route = get_object_or_404(Route, pk=selected_bus.route_id)
# 		stops = selected_bus_route.stops.all()
# 		json_origin_stop = json.dumps(selected_bus_route.origin.stop_name)

# 		stop_names = []
# 		json_stops = []
# 		for stop in stops:
# 			stop_names.append(stop.stop_name)
# 			# print(stop.stop_name)
# 			# json_stops.append(json.loads(stop.stop_name))

# 		json_stops = json.dumps(stop_names)
# 		# print(json_stops)

# 		context = {'stops': stops, 'json_stops' : json_stops, 'stop_names' : stop_names, 'json_origin_stop':json_origin_stop, 'buses' : buses, 'selected_bus' : selected_bus}


# 	return render(request, template, context)

def client_home(request):
	if request.user.is_superuser:
	    redirect_to = "/admin"
	    return HttpResponseRedirect(redirect_to)

	elif request.user.is_staff:
	    redirect_to = "/app_admin"
	    return HttpResponseRedirect(redirect_to)

	else:
		buses = Bus.objects.all()
		template = "client_home_1.html"
		# template = "client_home.html"
		context = {'buses' : buses}
		if request.method == 'POST':
			selected_bus = request.POST.get('bus_select')
			# print(selected_bus)
			selected_bus = get_object_or_404(Bus, pk=selected_bus)
			selected_bus_route = get_object_or_404(Route, pk=selected_bus.route_id)
			stops = selected_bus_route.stops.all()
			json_origin_stop_lat = json.dumps(selected_bus_route.origin.latitude)
			json_origin_stop_lon = json.dumps(selected_bus_route.origin.longitude)

			stop_lat = []
			stop_lon = []

			json_stops_lat = []
			json_stops_lon = []

			for stop in stops:
				stop_lat.append(stop.latitude)
				stop_lon.append(stop.longitude)
				# print(stop.stop_name)
				# json_stops.append(json.loads(stop.stop_name))

			json_stops_lat = json.dumps(stop_lat)
			json_stops_lon = json.dumps(stop_lon)
			# print(json_stops)

			context = {'stops': stops, 'json_stops_lat' : json_stops_lat, 'json_stops_lon' : json_stops_lon, 'json_origin_stop_lat':json_origin_stop_lat, 'json_origin_stop_lon':json_origin_stop_lon, 'buses' : buses, 'selected_bus' : selected_bus}


	return render(request, template, context)

def client_home1(request):
	context = {}
	template = "client_home.html"

	return render(request, template, context)


	# if request.method == 'POST':
	# 	selected_bus = get_object_or_404(Bus, pk=(request.POST.get('bus_id')))

	# else:
		

Never_Miss_The_Bus/Client/templates/Home.html
{% extends "registration/registration_base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Never Miss The Bus" %}{% endblock %}

{% block body %}
<body class="landing-page">
    <nav class="navbar navbar-transparent navbar-absolute">
    	<div class="container">
        	<!-- Brand and toggle get grouped for better mobile display -->
        	<div class="navbar-header">
        		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
            		<span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
        		</button>
        		<a class="navbar-brand" href="/">Never Miss The Bus</a>
        	</div>

        	<div class="collapse navbar-collapse" id="navigation-example">
        		<ul class="nav navbar-nav navbar-right">
    				<li>
		                <a href="https://www.facebook.com/siddharth.trivedi.29" target="_blank" class="btn btn-simple">
							<i class="fa fa-facebook-square"></i>
							Facebook
						</a>
		            </li>	
		            <li>
		                <a href="https://plus.google.com/110391960277280855223" target="_blank" class="btn btn-simple">
							<i class="fa fa-google-plus-square"></i>
							Google +
						</a>
		            </li>
        		</ul>
        	</div>
    	</div>
    </nav>

    <div class="wrapper">
        <div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&h=750&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450');">
            <div class="container">
                <div class="row">
					<div class="col-md-6">
						<h1 class="title"> Reach your stop on pefect time. </h1>
	                    <h4> No more bus misses and no more waiting at stops. Get real-time location of campus transit vehicles.  </h4>
	                    <br />
	                    {% if not request.user.is_authenticated %}
		                    <div>
			                    <div style="float: left;">
				                    <a href="{% url 'registration_register' %}" class="btn btn-danger btn-raised btn-lg">
										Register Now
									</a>
								</div>
								
								<div style="float: right;">
									<a href="{% url 'auth_login' %}" class="btn btn-success btn-raised btn-lg">
										Login Now
									</a>
								</div>
							</div>

						{% else %}
							<div>
								<a href="{% url 'client-app:client_home' %}" class="btn btn-success btn-raised btn-lg">
									Go to your dash
								</a>
							</div>
						{% endif %}
					</div>
                </div>
            </div>
        </div>

		<div class="main main-raised">
			<div class="container">
		    	<div class="section text-center section-landing">
	                <div class="row">
	                    <div class="col-md-8 col-md-offset-2">
	                        <h2 class="title">Project Vision </h2>
	                        <h5 class="description">Making the university transit system <b> real-time transparent </b> to the university people by tracking the vehicles’ locations and notifying the trippers when the tansit vehicle is around their stop. So that the tripper can reach at stop on perfect time.
</h5>
	                    </div>
	                </div>

					<div class="features">
						<div class="row">
		                    <div class="col-md-4">
								<div class="feature feature-primary">
									<i class="material-icons">my_location</i>
									<h4 class="title">Real-Time Location</h4>
			                        <p class="description"> Now you can exactly locate any campus transit vehicle in Google's Map API. </p>
								</div>

		                    </div>
		                    <div class="col-md-4">
								<div class="feature feature-success">
									<i class="material-icons">verified_user</i>
									<h4 class="title">Two-Step Registration</h4>
			                        <p class="description"> To get entry into the system any anonymous user must have to pass through two step registration system.  </p>
								</div>

		                    </div>
		                    <div class="col-md-4">
								<div class="feature feature-danger">
									<i class="material-icons">fingerprint</i>
									<h4 class="title">Secured with SHA1 </h4>
			                        <p class="description"> All users' passwords are encryted using SHA1 that ensures user's security. </p>
								</div>

		                    </div>
		                </div>
					</div>
	            </div>

	        	<div class="section text-center">
	                <h2 class="title">Something about me</h2>

					<div class="team">
						<div class="row">
							<div class="col-md-4" style="float: none; margin: 0 auto;">
			                    <div class="team-player">
			                        <img src={% static "img/Siddi_Profile_Pic.jpeg" %} alt="Thumbnail Image" class="img-raised img-circle" width="300" height="200">
			                        <h4 class="title"> Siddharth Trivedi <br />
										<small class="text-muted"> Android & Django Developer </small>
									</h4>
			                        <p class="description"> I had done small scale projects in Python, Java, VB.Net and ASP.Net. But I found that Python is cool. So I'm developing my current academic project based on real-time transit like NextBus with Python using Django Framework. And now I'm planning to move on Machine Learning. I juz love autonomous stuffs.</p>
			                    </div>
			                </div>
						</div>
					</div>

	            </div>
	        </div>

		</div>

	    <footer class="footer">
	        <div class="container">
	            <nav class="pull-left">
					<ul>
						<li>
							<a href="http://presentation.creative-tim.com">
							   About Project
							</a>
						</li>

					</ul>
	            </nav>
	            <div class="copyright pull-right">
	                &copy; 2016, made with <i class="fa fa-heart heart"></i> by <a href="https://www.facebook.com/siddharth.trivedi.29" target="_blank">Siddharth Trivedi</a>
	            </div>
	        </div>
	    </footer>

	</div>
</body>
{% endblock %}

Never_Miss_The_Bus/Client/templates/client_home.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href={% static "Material_Kit/img/favicon.ico" %}>
    <link rel="icon" type="image/ico" href={% static "Material_Kit/img/favicon.ico" %}>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title> {% block title %} Never Miss The Bus {% endblock %}</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link href={% static "Material_Kit/css/bootstrap.min.css" %} rel="stylesheet" />
    <link href={% static "Material_Kit/css/material-kit.css" %} rel="stylesheet"/>

    <!-- Custom CSS -->
    <style>
    html,
    body {
        height: 100%;
        width: 100%;
        padding: 0;
        margin: 0;
    }
    .over_map { position: absolute; top: 10px; right: 10px; z-index: 99; }
    
    .wrapper { height: 100%; width: 100%; }
    #map {
        height: 100%;
        width: 100%;
        position: fixed;
        /*bottom: 0px;*/
        /*top: 20%;*/
    }
    </style>

</head>

<body class="account">
    
    
    <div class="wrapper">
    <div class="over_map">
            {% if request.method == 'GET'%}
                <form action="" method="POST">{% csrf_token %}
                    <select name="bus_select" id="id_bus_select">
                    {% for bus in buses %}
                        <option value="{{bus.bus_id}}"> {{bus}} </option>
                    {% endfor %}
                    </select>
                    <input type="submit" value="GET STOPS" />
                </form>
            {% else %}
                <select name="stop_select" id="id_stop_select">
                {% for stop in stops %}
                        <option value="{{stop.stop_id}}"> {{stop}} </option>
                    {% endfor %}
                </select>
            {% endif %}
        </div>
        <div id="map" />
    </div>

    </div>


</body>
    <!--   Core JS Files   -->
    <script src={% static "Material_Kit/js/jquery.min.js" %} type="text/javascript"></script>
    <script src={% static "Material_Kit/js/bootstrap.min.js" %} type="text/javascript"></script>
    <script src={% static "Material_Kit/js/material.min.js" %}></script>

    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src={% static "Material_Kit/js/nouislider.min.js" %} type="text/javascript"></script>

    <!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
    <script src={% static "Material_Kit/js/bootstrap-datepicker.js" %} type="text/javascript"></script>

    <!-- Control Center for Material_Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
    <script src={% static "Material_Kit/js/material-kit.js" %} type="text/javascript"></script>
    <script src="https://cdn.firebase.com/js/client/2.4.2/firebase.js"></script>

    <script type="text/javascript">
        $().ready(function(){
            // the body of this function is in assets/material-kit.js
            $(window).on('scroll', materialKit.checkScrollForTransparentNavbar);
        });
    </script>
        <script>
    var myLatLng = {
        lat: 20.5937,
        lng: 78.9629
    };
    var map = null;

    function initMap() {
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: myLatLng
        });

        directionsDisplay.setMap(map);
        calculateAndDisplayRoute(directionsService, directionsDisplay);

        // document.getElementById('submit').addEventListener('click', function() {
        //     calculateAndDisplayRoute(directionsService, directionsDisplay);
        // });
    }

    var myFirebaseRef = new Firebase("https://nevermissbus.firebaseio.com/");

    var marker = null;
    var new_lat = 21.278018;
    var new_lng = 72.883816;
    myFirebaseRef.child("Coordinates/Lat").on("value", function(snapshot) {
        new_lat = snapshot.val();
        // autoUpdate();
    });

    myFirebaseRef.child("Coordinates/Lon").on("value", function(snapshot) {
        new_lng = snapshot.val();
        autoUpdate();
    });

    function autoUpdate() {
        var newPoint = new google.maps.LatLng(new_lat, new_lng);
        if (marker) {
            marker.setPosition(newPoint);
        } else {
            marker = new google.maps.Marker({
                position: newPoint,
                map: map,
                title: "Hello World"
            });
        }
    }

    function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var waypts = [];
        // var checkboxArray = document.getElementById('waypoints');

        var checkboxArray = {{json_stops|safe}};

        for (var i=0; i < checkboxArray.length ; i++) {
            waypts.push({
                location: checkboxArray[i],
                stopover: true
            });
        }

        var route = directionsService.route({
            // origin: 'Lalita Chowkadi, Vishal Nagar, Surat, Gujarat',
            // destination: 'Uka Tarsadia University Rd, Tarsadi, Gujarat ',
            origin: {{json_origin_stop|safe}},
            destination: 'Uka Tarsadia University Road',
            // destination: 'Mumbai',
            waypoints: waypts,
            optimizeWaypoints: true,
            travelMode: google.maps.TravelMode.DRIVING
        }, function(response, status) {
            if (status === google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
                // var route = response.routes[0];
                // var summaryPanel = document.getElementById('directions-panel');
                // summaryPanel.innerHTML = '';
                // // For each route, display summary information.
                // for (var i = 0; i < route.legs.length; i++) {
                //     var routeSegment = i + 1;
                //     summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment +
                //         '</b><br>';
                //     summaryPanel.innerHTML += route.legs[i].start_address + ' <br> <b> to <b/> <br>';
                //     summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
                //     summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
                // }

            } 
            else {
                window.alert('Directions request failed due to ' + status);
            }
        });
        autoUpdate();
    }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJvGXHOagT6ub1NHoDZaN8ca3zxP45Rkw&callback=initMap">
    </script>
</html>

Never_Miss_The_Bus/Client/templates/client_home_1.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href={% static "Material_Kit/img/favicon.ico" %}>
    <link rel="icon" type="image/ico" href={% static "Material_Kit/img/favicon.ico" %}>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title> {% block title %} Never Miss The Bus {% endblock %}</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" />

    <!-- CSS Files -->
    <link href={% static "Material_Kit/css/bootstrap.min.css" %} rel="stylesheet" />
    <link href={% static "Material_Kit/css/material-kit.css" %} rel="stylesheet"/>

    <!-- Custom CSS -->
    <style>
    html,
    body {
        height: 100%;
        width: 100%;
        padding: 0;
        margin: 0;
    }
    .over_map { 
        position: absolute; 
        z-index: 99;
        visibility: hidden;
    }
    
    .wrapper { height: 100%; width: 100%; }
    #map {
        height: 100%;
        width: 100%;
        position: fixed;
        transition: margin-left .5s;
        /*bottom: 0px;*/
        /*top: 20%;*/
    }
    .sidenav {
        width: 250px;
        position: absolute;
        z-index: 1;
        /*left: -240px;*/
        background-color: #FFF;
        opacity: 0.9;
        overflow-x: hidden;
        transition: 0.5s;
    }

    .sidenav a {
        padding: 8px 8px 8px 32px;
        text-decoration: none;
        font-size: 25px;
        color: #818181;
        display: block;
        transition: 0.3s
    }

    .sidenav a:hover, .offcanvas a:focus{
        color: rgb(42, 86, 86);
    }

    .closebtn {
        position: absolute;
        top: 0;
        right: 25px;
        font-size: 36px !important;
        margin-left: 50px;
        
    }

    @media screen and (max-height: 450px) {
      .sidenav {padding-top: 15px;}
      .sidenav a {font-size: 18px;}
    }
    </style>

</head>

<body>
    <nav class="navbar" style="background-color: rgba(5,60,60,0.81);">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a class="navbar-brand" href="/">Never Miss The Bus</a>
            </div>

            <a href="{% url 'auth_logout' %}"class="pull-right btn" style="color:rgb(212, 255, 255) ;background-color: rgba(13, 30, 30, 0.49);"> Logout </a>
            <div class="pull-right btn" style="color:rgb(212, 255, 255) ;background-color: rgba(13, 30, 30, 0.49);"> Welcome, {{ request.user.first_name }} {{ request.user.last_name }} </div>


            <!-- <div class="collapse navbar-collapse" id="navigation-example">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        
                    </li>   
                </ul>
            </div> -->
        </div>
        <!-- <span style="font-size:30px; cursor:pointer" onclick="openNav()">☰</span>     -->
    </nav>
    
    <div class="wrapper">
        <div class="container" style="width: 100%; height: 100%; padding-bottom: 100px;">

            <div class="over_map" id="openSideNav" style="font-size:30px; cursor:pointer; padding: 20px 0px 0px 20px;" onclick="openNav()">
                ☰
            </div>
            <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
                <div class="control" style="padding: 60px 10px 0px 20px; text-align: center;">
                    <form action="" method="POST">{% csrf_token %}
                        <select name="bus_select" id="id_bus_select" class="select form-control">
                        {% for bus in buses %}
                            <option value="{{bus.bus_id}}"> {{bus}} </option>
                        {% endfor %}
                        </select>
                        <br />
                        <button class="btn btn-raised btn-info" type="submit">
                        GET STOPS
                        </button>
                    </form>
                </div>
            </div>
            <div id="map">
            </div>
        </div>
    </div>
    <footer class="footer" style="position: fixed; background-color: rgba(5,60,60,0.81); color: white; ">
        <div class="container">
            <nav class="pull-left">
                <ul>
                    <li>
                        <a href="http://presentation.creative-tim.com">
                           About Project
                        </a>
                    </li>

                </ul>
            </nav>
            <div class="copyright pull-right">
                &copy; 2016, made with <i class="fa fa-heart heart"></i> by Siddharth Trivedi
            </div>
        </div>
        </footer>


</body>
    <!--   Core JS Files   -->
    <script src={% static "Material_Kit/js/jquery.min.js" %} type="text/javascript"></script>
    <script src={% static "Material_Kit/js/bootstrap.min.js" %} type="text/javascript"></script>
    <script src={% static "Material_Kit/js/material.min.js" %}></script>

    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src={% static "Material_Kit/js/nouislider.min.js" %} type="text/javascript"></script>

    <!--  Plugin for the Datepicker, full documentation here: http://www.eyecon.ro/bootstrap-datepicker/ -->
    <script src={% static "Material_Kit/js/bootstrap-datepicker.js" %} type="text/javascript"></script>

    <!-- Control Center for Material_Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
    <script src={% static "Material_Kit/js/material-kit.js" %} type="text/javascript"></script>
    <script src="https://cdn.firebase.com/js/client/2.4.2/firebase.js"></script>

    <script type="text/javascript">
        $().ready(function(){
            // the body of this function is in assets/material-kit.js
            $(window).on('scroll', materialKit.checkScrollForTransparentNavbar);
        });
    </script>
    <script>
        var myLatLng = {
            lat: 20.5937,
            lng: 78.9629
        };
        var map = null;

        function initMap() {
            var directionsService = new google.maps.DirectionsService;
            var directionsDisplay = new google.maps.DirectionsRenderer;
            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 4,
                center: myLatLng,
                mapTypeControl: false,
            });

            directionsDisplay.setMap(map);
            calculateAndDisplayRoute(directionsService, directionsDisplay);

            // document.getElementById('submit').addEventListener('click', function() {
            //     calculateAndDisplayRoute(directionsService, directionsDisplay);
            // });
        }

        var myFirebaseRef = new Firebase("https://nevermissbus.firebaseio.com/");

        var marker = null;
        var new_lat = 21.278018;
        var new_lng = 72.883816;
        myFirebaseRef.child("Coordinates/Lat").on("value", function(snapshot) {
            new_lat = snapshot.val();
            // autoUpdate();
        });

        myFirebaseRef.child("Coordinates/Lon").on("value", function(snapshot) {
            new_lng = snapshot.val();
            autoUpdate();
        });

        function autoUpdate() {
            var newPoint = new google.maps.LatLng(new_lat, new_lng);
            if (marker) {
                marker.setPosition(newPoint);
            } else {
                marker = new google.maps.Marker({
                    position: newPoint,
                    map: map,
                    title: "Bus Name: {{ selected_bus }}",
                    icon: "{% static 'img/bus_stop_geolocalization.png' %}",

                });
            }
        }

        function calculateAndDisplayRoute(directionsService, directionsDisplay) {
            var waypts = [];
            // var checkboxArray = document.getElementById('waypoints');

            var json_stops_lat_array = {{json_stops_lat|safe}};
            var json_stops_lon_array = {{json_stops_lon|safe}};

            for (var i=0; i < json_stops_lat_array.length ; i++) {
                waypts.push({
                    location: new google.maps.LatLng(json_stops_lat_array[i],json_stops_lon_array[i]),
                    stopover: true
                });
            }

            var origin_stop_lat = {{json_origin_stop_lat|safe}};
            var origin_stop_lon = {{json_origin_stop_lon|safe}};
            var route = directionsService.route({
                origin: new google.maps.LatLng(origin_stop_lat, origin_stop_lon),
                // destination: 'Uka Tarsadia University Rd, Tarsadi, Gujarat ',
                // origin: new google.maps.LatLng(origin_stop_lat, origin_stop_lat),
                destination: 'Uka Tarsadia University Road',
                // destination: 'Mumbai',
                 waypoints: waypts,
                // optimizeWaypoints: true,
                travelMode: google.maps.TravelMode.DRIVING
            }, function(response, status) {
                if (status === google.maps.DirectionsStatus.OK) {
                    directionsDisplay.setDirections(response);
                    // var route = response.routes[0];
                    // var summaryPanel = document.getElementById('directions-panel');
                    // summaryPanel.innerHTML = '';
                    // // For each route, display summary information.
                    // for (var i = 0; i < route.legs.length; i++) {
                    //     var routeSegment = i + 1;
                    //     summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment +
                    //         '</b><br>';
                    //     summaryPanel.innerHTML += route.legs[i].start_address + ' <br> <b> to <b/> <br>';
                    //     summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
                    //     summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
                    // }

                } 
                else {
                    window.alert('Directions request failed due to ' + status);
                }
            });
            autoUpdate();
        }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJvGXHOagT6ub1NHoDZaN8ca3zxP45Rkw&callback=initMap">
    </script>

    <script>
        var map = document.getElementById("map");
        function openNav() {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("openSideNav").style.visibility = 'hidden';
            document.getElementById("mySidenav").removeEventListener('webkitTransitionEnd', showOpenSideNav);
            
        }

        function showOpenSideNav(){
            document.getElementById("openSideNav").style.visibility = 'visible';
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("map").style.marginLeft= "0";

            document.getElementById("mySidenav").addEventListener('webkitTransitionEnd', showOpenSideNav, false);

            // document.getElementById("mySidenav").removeEventListener('webkitTransitionEnd', showOpenSideNav);
        }
        $("#map").click(function(e){
            closeNav();
        });

    </script>
</html>