Never_Miss_The_Bus/App_Admin/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.conf.urls import url
from . import views

# app_name = 'App_Admin'

urlpatterns = [
	# url(r'^user/$',staff_member_required(views.UserList.as_view(template_name="model_list.html")), name = "user_list"),
	url(r'^route/$',staff_member_required(views.RouteList.as_view(template_name="model_list.html")), name = "route_list"),
	url(r'^stop/$',staff_member_required(views.StopList.as_view(template_name="model_list.html")), name = "stop_list"),
	url(r'^bus/$',staff_member_required(views.BusList.as_view(template_name="model_list.html")), name = "bus_list"),
	url(r'^reporter/$',staff_member_required(views.ReporterList.as_view(template_name="model_list.html")), name = "reporter_list"),
	url(r'^request/$',staff_member_required(views.CoordRequestList.as_view(template_name="model_list.html")), name = "request_list"),
	# url(r'^bus/(?P<pk>[0-9]+)/$',staff_member_required(views.BusUpdate.as_view()), name = "update-bus"),

	# url(r'^user/add/$',staff_member_required(views.UserCreate.as_view()), name = "user_create"),
	url(r'^route/add/$',staff_member_required(views.RouteCreate.as_view()), name = "route_create"),
	url(r'^stop/add/$',staff_member_required(views.StopCreate.as_view()), name = "stop_create"),
	url(r'^bus/add/$',staff_member_required(views.BusCreate.as_view()), name = "bus_create"),
	url(r'^request/add/$',staff_member_required(views.CoordRequestCreate.as_view()), name = "request_create"),
	url(r'^reporter/add/$',staff_member_required(views.ReporterCreate.as_view()), name = "reporter_create"),

	# url(r'^user/update/(?P<pk>[0-9]+)/$',staff_member_required(views.UserUpdate.as_view()), name = "user_update"),
	url(r'^route/update/(?P<pk>[0-9]+)/$',staff_member_required(views.RouteUpdate.as_view()), name = "route_update"),
	url(r'^stop/update/(?P<pk>[0-9]+)/$',staff_member_required(views.StopUpdate.as_view()), name = "stop_update"),
	url(r'^bus/update/(?P<pk>[0-9]+)/$',staff_member_required(views.BusUpdate.as_view()), name = "bus_update"),
	url(r'^request/update/(?P<pk>[0-9]+)/$',staff_member_required(views.CoordRequestUpdate.as_view()), name = "request_update"),
	url(r'^reporter/update/(?P<pk>[0-9]+)/$',staff_member_required(views.ReporterUpdate.as_view()), name = "reporter_update"),


	# url(r'^user/delete/(?P<pk>[0-9]+)/$',staff_member_required(views.UserDelete.as_view()), name = "user_delete"),
	url(r'^route/delete/(?P<pk>[0-9]+)/$',staff_member_required(views.RouteDelete.as_view()), name = "route_delete"),
	url(r'^stop/delete/(?P<pk>[0-9]+)/$',staff_member_required(views.StopDelete.as_view()), name = "stop_delete"),
	url(r'^bus/delete/(?P<pk>[0-9]+)/$',staff_member_required(views.BusDelete.as_view()), name = "bus_delete"),
	url(r'^request/delete/(?P<pk>[0-9]+)/$',staff_member_required(views.CoordRequestDelete.as_view()), name = "request_delete"),
	url(r'^reporter/delete/(?P<pk>[0-9]+)/$',staff_member_required(views.ReporterDelete.as_view()), name = "reporter_delete"),

	url(r'^request/accept/$',staff_member_required(views.accept_request), name = "accept_request"),
	url(r'^request/deny/$',staff_member_required(views.deny_request), name = "deny_request"),
	

	url(r'^$',staff_member_required(views.dashboard), name = "Dashboard"),
]

Never_Miss_The_Bus/Client/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from Client import views

urlpatterns = [
	url(r'^$', login_required(views.client_home), name='client_home'),
	url(r'^test/$', views.client_home1),
]

Never_Miss_The_Bus/Never_Miss_The_Bus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
urlpatterns = [
    #django urls
    url(r'^admin/', include(admin.site.urls)),
    #django-registration-redux urls
    url(r'^accounts/', include('registration.backends.default.urls')),
    #Custom apps' urls
    url(r'^app_admin/', include('App_Admin.urls', app_name="App_Admin",namespace='admin-app')),
    url(r'^client/', include('Client.urls', app_name="Client_App",namespace='client-app')),
    url(r'^$', views.home, name='home'),
]

Never_Miss_The_Bus/registration/urls.py
"""
Backwards-compatible URLconf for existing django-registration
installs; this allows the standard ``include('registration.urls')`` to
continue working, but that usage is deprecated and will be removed for
django-registration 1.0. For new installs, use
``include('registration.backends.default.urls')``.

"""

import warnings

warnings.warn("include('registration.urls') is deprecated; use include('registration.backends.default.urls') instead.",
              DeprecationWarning)

from .backends.default.urls import *  # NOQA

Never_Miss_The_Bus/App_Admin/models.py
from django.db import models
from django.contrib.auth.models import User as Auth_User
from django.core.urlresolvers import reverse

# Create your models here.

class Stop(models.Model):
	stop_id = models.AutoField(
		primary_key=True, 
		editable=False,
		verbose_name='Stop ID'
	)

	stop_name = models.CharField(
		"Stop Name", 
		max_length=50,
		blank=False,
		unique=True,
	)

	latitude = models.CharField(
		"Latitude",
		max_length=10,
		blank=False,
	)

	longitude = models.CharField(
		"Longitude",
		max_length=10,
		blank=False,
	)

	def __str__(self):
		return self.stop_name

	def get_absolute_url_for_update(self):
		return reverse('App_Admin:stop_update', args=[str(self.stop_id)] )

	def get_absolute_url_for_delete(self):
		return reverse('App_Admin:stop_delete', args=[str(self.stop_id)] )

	def get_fileds(self):
		return [field.verbose_name for field in self._meta.fields]

	def get_field_values(self):
		return [(field.value_to_string(self)) for field in self._meta.fields]

	class Meta:
		verbose_name = "Stops"

class Route(models.Model):
	route_id = models.AutoField(
		primary_key=True, 
		editable=False,
		verbose_name='Route ID'
	)
	route_name = models.CharField(
		"Route Name", 
		max_length=50,
		blank=False,
		unique=True,
	)

	origin = models.ForeignKey(
		Stop,
		blank=False,
		related_name="%(app_label)s_origin_stop_related",
		verbose_name='Origin Stop',
	)

	stops = models.ManyToManyField(
		Stop,
		blank=False,
		verbose_name='Stops')

	def __str__(self):
		return self.route_name

	def get_absolute_url_for_update(self):
		return reverse('App_Admin:route_update', args=[str(self.route_id)] ) #"/app_admin/route/%i/" % self.id

	def get_absolute_url_for_delete(self):
		return reverse('App_Admin:route_delete', args=[str(self.route_id)] )

	def get_fileds(self):
		return [field.verbose_name for field in self._meta.fields]

	def get_field_values(self):
		return [(field.value_to_string(self)) for field in self._meta.fields]

	class Meta:
		verbose_name = "Routes"

class Bus(models.Model):
	bus_id = models.AutoField(
		verbose_name='ID',
		primary_key=True, 
		editable=False
	)
	bus_name = models.CharField(
		"Bus Name",
		unique=True,
		max_length=30,
		blank=False
	)
	route = models.ForeignKey(
		Route, 
		on_delete=models.CASCADE,
		verbose_name='Route',
		blank=False
	)

	statuses = (
		('REG', 'Registered'),
		('OPN', 'Open/Not Registered'),
	)
	status = models.CharField(
		'Status',
		choices=statuses, 
		max_length=3, 
		default='OPN',
		blank=False,
	)

	def set_status(self, status = 'OPN'):
		self.status = status

	def get_fileds(self):
		return [field.verbose_name for field in self._meta.fields]

	def get_field_values(self):
		return [(field.value_to_string(self)) for field in self._meta.fields]

	def __str__(self):
		return self.bus_name

	def get_absolute_url_for_update(self):
		return reverse('App_Admin:bus_update', args=[str(self.bus_id)] )

	def get_absolute_url_for_delete(self):
		return reverse('App_Admin:bus_delete', args=[str(self.bus_id)] )

	class Meta:
		verbose_name = "Buses"


# class User(Auth_User):

# 	def get_absolute_url_for_update(self):
# 		return reverse('App_Admin:user_update', args=[str(self.id)] )

# 	def get_absolute_url_for_delete(self):
# 		return reverse('App_Admin:user_delete', args=[str(self.id)] )

# 	def get_fileds(self):
# 		gen = [field for field in self._meta.fields]
# 		for genfield in gen:
# 			if genfield.name not in ('last_modified', 'date_joined', 'last_login', 'is_superuser', 'password', 'staff_status','active','user_ptr'):
# 				yield genfield.verbose_name

# 	def get_field_values(self):
# 		gen = [field for field in self._meta.fields]
# 		for genfield in gen:
# 			if genfield.name not in ('last_modified', 'date_joined', 'last_login', 'is_superuser', 'password', 'staff_status','active','user_ptr'):
# 				yield genfield.value_to_string(self)

# 	def __str__(self):
# 		return self.username

# 	class Meta:
# 		verbose_name = "Users"


class Coord_Reporter_Request(models.Model):
	request_id = models.AutoField(
		primary_key=True, 
		editable=False
	)

	user = models.OneToOneField(
		Auth_User,
		on_delete = models.CASCADE,
		blank=False,
		verbose_name='Requested by',
		)

	requestedfor_bus_number = models.ForeignKey(
		Bus, 
		on_delete=models.CASCADE,
		blank=False,
		verbose_name='Requesting for bus'
	)

	request_created_date_time = models.DateTimeField(
		auto_now_add=True,
		verbose_name='Request created on'
	)

	respond_date_time = models.DateTimeField( 
		null=True
	)

	statuses = (
		('NVR', 'Not Verified'),
		('DND', 'Denied'),
	)

	respond_status = models.CharField(
		max_length=3, 
		choices= statuses,
		default='NVR',

	)

	def get_absolute_url_for_accept(self):
		return reverse('App_Admin:accept_request')

	def get_absolute_url_for_deny(self):
		return reverse('App_Admin:deny_request')

	def get_absolute_url_for_update(self):
		return reverse('App_Admin:request_update', args=[str(self.request_id)] )

	def get_absolute_url_for_delete(self):
		return reverse('App_Admin:request_delete', args=[str(self.request_id)] )

	def get_fileds(self):
		return [field.verbose_name for field in self._meta.fields]

	def get_field_values(self):
		return [field.value_to_string(self) for field in self._meta.fields]

	class Meta:
		verbose_name = "Coordinates Reporting Requests"


class Coord_Reporter(models.Model):
	reporter_id = models.AutoField(
		primary_key=True, 
		editable=False
	)

	user = models.OneToOneField(
		Auth_User,
		on_delete = models.CASCADE,
		blank=False,
		verbose_name='Reporter',
	)

	allocated_bus = models.ForeignKey(
		Bus,
	)

	acceptance_date = models.DateTimeField(
		auto_now_add=True,
	)

	accepted_by = models.ForeignKey(
		Auth_User,
		related_name = 'accepted_by',
		on_delete = models.CASCADE,
	)

	def get_absolute_url_for_update(self):
		return reverse('App_Admin:reporter_update', args=[str(self.reporter_id)] )

	def get_absolute_url_for_delete(self):
		return reverse('App_Admin:reporter_delete', args=[str(self.reporter_id)] )

	def get_fileds(self):
		return [field.verbose_name for field in self._meta.fields]

	def get_field_values(self):
		return [(field.value_to_string(self)) for field in self._meta.fields]

	def __str__(self):
		return str(self.user.username)	

	class Meta:
		verbose_name = "Coordinates Reporters"

Never_Miss_The_Bus/App_Admin/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models
from django.contrib.auth.models import User as Auth_User
from django.utils.translation import ugettext_lazy as tolabel

class User_Form(UserCreationForm):
	class Meta:
		model = Auth_User
		fields = ['first_name', 'last_name', 'username','email']
		widgets = { 
            'username': forms.TextInput(attrs={'required': 'required'}),
            'first_name': forms.TextInput(attrs={'required': 'required'}),
            'last_name': forms.TextInput(attrs={'required': 'required'}),
            'password1': forms.TextInput(attrs={'required': 'required', 'type' : 'password', 'id' : 'password', 'pattern':'(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}', 'title':'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters'}),
            'password2': forms.TextInput(attrs={'required': 'required', 'type' : 'password', 'id' : 'confirm_password'}),
            'email' : forms.TextInput(attrs={'required': 'required', 'type': 'email', 'pattern':'[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$', 'title': 'Invalid email address.'}), 
        }   
		# error_message={
		# 'first_name': {
		# 		'required': _("Please let us know what to call you!"),
		# 	},
		# }

class Route_Form(forms.ModelForm):
	class Meta:
		model = models.Route
		fields = ['route_name','origin' ,'stops']

class Stop_Form(forms.ModelForm):
	class Meta:
		model = models.Stop
		fields = ['stop_name', 'latitude', 'longitude']

class Bus_Form(forms.ModelForm):
	class Meta:
		model = models.Bus
		fields = ['bus_name', 'route']

class Coord_Reporter_Request_Form(forms.ModelForm):
	class Meta:
		model = models.Coord_Reporter_Request
		fields = ['requestedfor_bus_number', 'user']
		labels={
			'requestedfor_bus_number' : tolabel('Requesting for bus'),
		}

	def __init__(self, *args, **kwargs):
		super(Coord_Reporter_Request_Form, self).__init__(*args, **kwargs)
		if self.instance:
			self.fields["requestedfor_bus_number"].queryset = models.Bus.objects.filter(status='OPN')
			all_users = Auth_User.objects.all()
			current_reporters = models.Coord_Reporter.objects.all()
			current_requests = models.Coord_Reporter_Request.objects.all()
			reporter_excluded_qs = all_users.exclude(id__in = current_reporters.values_list('user'))
			self.fields["user"].queryset = reporter_excluded_qs.exclude(id__in = current_requests.values_list('user'))


class Reporter_Form(forms.ModelForm):
	class Meta:
		model = models.Coord_Reporter
		# readonly_fields = ['reporter_id', 'allocated_bus', 'acceptance_date', 'verifier']
		# fields = []
		fields = ['allocated_bus', 'user', 'accepted_by']
		# for i in model._meta.fields:
		# 	print(fields.append(str(i)))

Never_Miss_The_Bus/App_Admin/templates/add.html
{% extends "Admin_Base.html" %}

{% block title %}
{{ title }}
{% endblock %}
{% block breadcrumbs %}
    <li> <a href="/app_admin/"> Dashboard </a> </li>
    <li class="active"> {{title}} </li>
{% endblock %}
{% block content %}
{% if form %}
<!-- Form Errors -->
{% if form.errors %}
<ul class="errors">
    {% for error in form.errors %}
    <li>
        {{ error }}
    </li>
    {% endfor %}
</ul>
{% endif %}
<!-- Display Form -->
<form method="POST">
    {% csrf_token %}
    {% load custome_filters %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="card">
                    <div class="header">
                        <h4 class="title">
                            {{title}}
                        </h4>
                        <div class="content">
                            <div class="row">
                                {% for field in form %}
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            {{field.label}}
                                        </label>
                                        {{field|addcss:"form-control"}}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <div class="row" style="line-height: 100px">
                                <div class="pull-right">
                                    <a class="btn btn-info btn-fill" href="/app_admin/">
                                        Cancel
                                    </a>
                                    <!-- <button class="btn btn-info btn-fill" type="submit">
                                        Save and add another
                                    </button> -->
                                    <button class="btn btn-info btn-fill" type="submit" href="/app_admin/">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endif %}
{% endblock%}

Never_Miss_The_Bus/App_Admin/templates/confirm_delete.html
{% extends "Admin_Base.html" %}

{% block breadcrumbs %}
    <li> <a href="/app_admin/"> Dashboard </a> </li>
    <li class="active"> {{title}} </li>
{% endblock %}
{% block title%}
	{{title}}
{% endblock %}
{% block content %}
	<form action="" method="post">{% csrf_token %}
	    <p>Are you sure you want to delete "{{ object }}"?</p>
	    <input type="submit" value="Confirm" />
	</form>	
{% endblock %}

Never_Miss_The_Bus/App_Admin/templates/create_form.html
{% extends "Admin_Base.html" %} {% load crispy_forms_tags %} {% block title %} {{ title }} {% endblock %} {% block breadcrumbs %}
<li> <a href="/app_admin/"> Dashboard </a> </li>
<li class="active"> {{title}} </li>
{% endblock %} {% block content %} {% if form %}
<!-- Form Errors -->
<!-- {% if form.errors %}
<ul class="errors">
    {% for k, message in form.errors.items %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %} -->
<!-- Display Form -->
<form method="POST">
    {% csrf_token %} {% load custom_filters %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="card">
                    <div class="header">
                        <h4 class="title">
                            {{title}}
                        </h4>
                        <div class="content">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        {{form | crispy}}
                                    </div>
                                </div>
                                <!-- {% for field in form %}
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>
                                            {{field.label}}
                                        </label>
                                        {{field|addcss:"form-control"}} {{ field.errors }}
                                    </div>
                                </div>
                                {% endfor %} -->
                            </div>
                            <div class="row" style="line-height: 100px">
                                <div class="pull-right">
                                    <a class="btn btn-info btn-fill" href="..">
                                        Cancel
                                    </a>
                                    <button class="btn btn-info btn-fill" type="submit">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endif %} 
{% endblock%} 
{% block JavaScript %}
<!-- console.log("Hello"); -->
$(document).ready(function(){
    $('#id_origin').on('change',function() {
        var $options = $("#id_origin > option").clone();
        $('#id_stops option').remove();
        $('#id_stops').append($options);
        var selected_stop = $(this).find(':selected').attr('value');
        $("#id_stops option[value="+selected_stop+"]").remove();
        $("#id_stops option[value='']").remove();
        
    });
});

{%endblock%}

Never_Miss_The_Bus/App_Admin/templates/dashboard.html
{% extends "Admin_Base.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="header">
                    <h4 class="title">
                        Application Administration
                    </h4>
                    <p class="category">
                        All tabels inside the application
                    </p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover table-striped">
                        <tbody>
                            {% for i in app_models %}
                            {% if i != 'route-stop relationship' and i != 'Users' %}
                            <tr>
                                <td>
                                    <div style="line-height: 30px">
                                        {{i}}
                                        <div class="pull-right">
                                            
                                            <a class="btn btn-info " href="/app_admin/{% cycle 'stop' 'route' 'bus' 'request' 'reporter' as urls %}/add/" 
                                            style="line-height: 10px;">
                                                <div class="pe-7s-plus" style="font-size: 15px; padding-right: 10px;float: left;">
                                                </div>
                                                <div style="font-size: 15px;float: right; line-height: 15px;">Add</div>
                                            </a>
                                            
                                            
                                            <a class="btn btn-info" href="{% cycle 'stop' 'route' 'bus' 'request' 'reporter' as urls %}/" style="line-height: 10px; margin-left: 10px">
                                                <div class="pe-7s-config" style="font-size: 15px; padding-right: 10px; float: left;">
                                                </div>
                                                <div style="font-size: 15px;float: right; line-height: 15px;">View</div>
                                            </a>
                                        </div>
                                        
                                    </div>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Never_Miss_The_Bus/App_Admin/templates/model_list.html
{% extends "Admin_Base.html"%} {% block title%} {{title}} {% endblock %} {% block breadcrumbs %}
<li> <a href="/app_admin/"> Dashboard </a> </li>
<li class="active"> {{title}} </li>
{% endblock %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">
                        {{title}}
                    </h4>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover">
                        {% for obj in object_list %} {% if forloop.first %}
                        <thead>
                            <tr>
                                {% for fld in obj.get_fileds %}
                                <th> {{fld}} </th>
                                {% endfor %}
                                <th style="text-align: center;"> Actions </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% endif %}
                            <tr>
                                {% for val in obj.get_field_values %}
                                <td> <small> {{ val }} </small> </td>
                                {% endfor %}
                                <td>
                                    <a class="btn btn-info" href="{{obj.get_absolute_url_for_update }}" style="line-height: 10px;">
                                        <div class="pe-7s-config" style="font-size: 15px; padding-right: 10px;float: left;">
                                        </div>
                                        <div style="font-size: 15px;float: right; line-height: 15px;">Update</div>
                                    </a>
                                    <a class="btn btn-danger" href="{{obj.get_absolute_url_for_delete }}" style="line-height: 10px; margin-left: 10px">
                                        <div class="pe-7s-close-circle" style="font-size: 15px; padding-right: 10px; float: left;">
                                        </div>
                                        <div style="font-size: 15px;float: right; line-height: 15px;">Delete</div>
                                    </a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td> No entries yet.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div style="margin-left: 20px">
                        <a class="btn btn-info" href="add/" style="line-height: 10px;">
                            <div class="pe-7s-plus" style="font-size: 15px; padding-right: 10px;float: left;">
                            </div>
                            <div style="font-size: 15px;float: right; line-height: 15px;">Add</div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Never_Miss_The_Bus/App_Admin/templates/route_register.html
<!DOCTYPE html>
<html>
<head>
	<title>Route Registration</title>
</head>
<body>
	<center>
		<h1> Route Registration </h1>
		<form method="POST" action=""> {% csrf_token %}
			{{form.as_p}} 
			<input type="submit" value="Register" />
		</form>
		
	</center>
</body>
</html>

Never_Miss_The_Bus/App_Admin/templates/table_view.html
{% extends "Admin_Base.html" %}

{% block content %}
	{{table.as_table}}
{% endblock %}

Never_Miss_The_Bus/App_Admin/templates/update_form.html
 {% extends "Admin_Base.html" %} 
  {% load crispy_forms_tags %}
 {% block title %} {{ title }} {% endblock %} 
 {% block breadcrumbs %}
<li> <a href="/app_admin/"> Dashboard </a> </li>
<li class="active"> {{title}} </li>
{% endblock %} 

{% block content %} 
{% if form %}
<!-- Form Errors -->
{% if form.errors %}
<ul class="errors">
    
</ul>
{% endif %}
<!-- Display Form -->
<form method="POST">
    {% csrf_token %} {% load custome_filters %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="card">
                    <div class="header">
                        <h4 class="title">
                            {{title}}
                        </h4>
                        <div class="content">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                    	{{form | crispy}}
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="line-height: 100px">
                                <div class="pull-right">
                                    <a class="btn btn-info btn-fill" href="/app_admin/">
                                        Cancel
                                    </a>
                                    <!-- <button class="btn btn-info btn-fill" type="submit">
                                        Save and add another
                                    </button> -->
                                    <button class="btn btn-info btn-fill" type="submit" href="/app_admin/">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endif %} {% endblock%}
{% block JavaScript %}
<!-- console.log("Hello"); -->
$(document).ready(function(){
    $('#id_origin').on('change',function() {
        var $options = $("#id_origin > option").clone();
        $('#id_stops option').remove();
        $('#id_stops').append($options);
        var selected_stop = $(this).find(':selected').attr('value');
        $("#id_stops option[value="+selected_stop+"]").remove();
        $("#id_stops option[value='']").remove();
        
    });
});

{%endblock%}